name: Push to master

on:
  push:
    branches:
      - master

concurrency:
  group: master
  cancel-in-progress: true

jobs:
  deploy-or-die:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Deploy security rules
        run: |
            sudo npm install -g firebase-tools@^13
            sudo npm install -g firebase-bolt
            firebase-bolt < security-rules.bolt > security-rules.json
            firebase deploy --token=$FIREBASE_TOKEN --only database
        env: 
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}        
      - name: Deploy admin
        run: |
            cd admin
            sed -i "s/bot_token_from_ci/$SLACK_BOT_TOKEN/" src/environments/environment.ts
            npm install
            sudo npm install -g @angular/cli
            firebase experiments:enable webframeworks
            ng deploy
        env: 
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }} 
            SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }} 
      - name: Deploy functions
        run: |
            cd functions
            npm install
            cd ..
            firebase deploy --token=$FIREBASE_TOKEN --only functions
        env: 
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}            
      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: /home/runner/.npm/_logs      
